[loglevel]
ethereum = "info"

[chain]
id = 42
stateDB = "~/validator3/"
stateDBInMemory = false
transactionDB = ""
transactionDBInMemory = true
monitorDB = "~/validator3mon/"
monitorDBInMemory = false

[bootnode]
listeningAddress = "0.0.0.0:4245"
cacheSize = 20

[transport]
upnp=false
originLimit = 50
privateKey = "dddddddddddddddddddddddddddddddd"
bootNodeAddresses = "0000002a|029570051a8573e865af31a066eb100e7744bcbd05d814e899a763500163675be9@127.0.0.1:4242"
p2pListeningAddress = "0.0.0.0:4346"
discoveryListeningAddress = "0.0.0.0:4447"
localStateListeningAddress = "0.0.0.0:8887"
peerLimitMax = 24
peerLimitMin = 3

[monitor]
batchSize = 1000
interval = "7s"
timeout = "1h"

[ethereum]
defaultAccount = "0x16564cF3e880d9F5d09909F51b922941EbBbC24d"
endpoint = "http://localhost:8545"
endpointPeers = 0
keystore = "assets/test/keys"
timeout = "1h"
passcodes = "assets/test/passcodes.txt"
testEther = "f000000000000000000"
finalityDelay = 2
retryCount = 3
retryDelay = "5s"
startingBlock = 1
registryAddress = "0x0b1f9c2b7bed6db83295c7b5158e3806d67ec5bc"

[edge]
ethTimeout = "5s"

[utils]
status = true

[validator]
rewardAccount = "0x16564cF3e880d9F5d09909F51b922941EbBbC24d"
rewardCurveSpec = 1
symmetricKey = "someSuperFancySecretThatWillBeHashed"

[firewalld]
enabled = false
socketFile = "/tmp/alicenet_firewalld"
