logging = "localRPC=info,gossipbus=info,utils=info,services=info,ethereum=info,main=warn,validator=info,monitor=info,deploy=info,consensus=debug,peerMan=info,muxHandler=info,p2pmux=info,app=error,transport=error,dman=info,status=info,db=info,yamux=error,badger=error,monitor_bus=error"

[chain]
id = 42
stateDB = "~/validator1/"
stateDBInMemory = false
transactionDB = ""
transactionDBInMemory = true
monitorDB = "~/validator1mon/"
monitorDBInMemory = false

[bootnode]
listeningAddress = "0.0.0.0:4243"
cacheSize = 20

[transport]
originLimit = 50
privateKey = "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
bootNodeAddresses = "0000002a|029570051a8573e865af31a066eb100e7744bcbd05d814e899a763500163675be9@bootnode:4242"
p2pListeningAddress = "0.0.0.0:4344"
discoveryListeningAddress = "0.0.0.0:4445"
localStateListeningAddress = "0.0.0.0:8885"
peerLimitMax = 24
peerLimitMin = 3
upnp=false

[monitor]
batchSize = 1000
interval = "7s"
timeout = "1h"

[ethereum]
defaultAccount = "0x615695C4a4D6a60830e5fca4901FbA099DF26271"
endpoint = "http://geth:8545"
endpointPeers = 0
keystore = "assets/test/keys"
timeout = "1h"
passcodes = "assets/test/passcodes.txt"
testEther = "f000000000000000000"
finalityDelay = 2
retryCount = 3
retryDelay = "5s"
startingBlock = 1
registryAddress = "0x0b1f9c2b7bed6db83295c7b5158e3806d67ec5bc"

[edge]
ethTimeout = "5s"

[utils]
status = true

[validator]
rewardAccount = "0x615695C4a4D6a60830e5fca4901FbA099DF26271"
rewardCurveSpec = 1
symmetricKey = "someSuperFancySecretThatWillBeHashed"

[firewalld]
enabled = false
socketFile = "/tmp/alicenet_firewalld"
