#logging = "localRPC=info,gossipbus=info,utils=info,services=info,ethereum=info,main=warn,validator=info,monitor=info,deploy=info,consensus=debug,peerMan=info,muxHandler=info,p2pmux=info,app=info,transport=info,dman=info,status=info,db=info,yamux=error,badger=error,monitor_bus=error"

[chain]
id = 42
stateDB = "~/validator4/"
stateDBInMemory = false
transactionDB = ""
transactionDBInMemory = true
monitorDB = "~/validator4mon/"
monitorDBInMemory = false

[bootnode]
listeningAddress = "0.0.0.0:4242"
cacheSize = 20

[transport]
upnp=false
originLimit = 50
privateKey = "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
bootNodeAddresses = "0000002a|029570051a8573e865af31a066eb100e7744bcbd05d814e899a763500163675be9@bootnode:4242"
p2pListeningAddress = "0.0.0.0:5343"
discoveryListeningAddress = "0.0.0.0:5444"
localStateListeningAddress = "0.0.0.0:8888"
peerLimitMax = 24
peerLimitMin = 3

[monitor]
batchSize = 1000
interval = "7s"
timeout = "1h"

[ethereum]
defaultAccount = "0x546F99F244b7B58B855330AE0E2BC1b30b41302F"
endpoint = "http://geth:8545"
endpointPeers = 0
keystore = "assets/test/keys"
timeout = "5s"
passcodes = "assets/test/passcodes.txt"
testEther = "f000000000000000000"
finalityDelay = 2
retryCount = 3
retryDelay = "5s"
startingBlock = 1
registryAddress = "0x0b1f9c2b7bed6db83295c7b5158e3806d67ec5bc"

[edge]
ethTimeout = "5s"

[utils]
status = true

[validator]
rewardAccount = "0x546F99F244b7B58B855330AE0E2BC1b30b41302F"
rewardCurveSpec = 1
symmetricKey = "someSuperFancySecretThatWillBeHashed"

[firewalld]
enabled = false
socketFile = "/tmp/alicenet_firewalld"
