/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { OnEvent, TypedEvent, TypedEventFilter, TypedListener } from "./common";

export interface AdminErrorCodesInterface extends utils.Interface {
  contractName: "AdminErrorCodes";
  functions: {
    "ADMIN_SENDER_MUST_BE_ADMIN()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "ADMIN_SENDER_MUST_BE_ADMIN",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "ADMIN_SENDER_MUST_BE_ADMIN",
    data: BytesLike
  ): Result;

  events: {};
}

export interface AdminErrorCodes extends BaseContract {
  contractName: "AdminErrorCodes";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AdminErrorCodesInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    ADMIN_SENDER_MUST_BE_ADMIN(overrides?: CallOverrides): Promise<[string]>;
  };

  ADMIN_SENDER_MUST_BE_ADMIN(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    ADMIN_SENDER_MUST_BE_ADMIN(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    ADMIN_SENDER_MUST_BE_ADMIN(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    ADMIN_SENDER_MUST_BE_ADMIN(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
