/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { OnEvent, TypedEvent, TypedEventFilter, TypedListener } from "./common";

export interface Base64ErrorCodesInterface extends utils.Interface {
  contractName: "Base64ErrorCodes";
  functions: {
    "BASE64_INVALID_INPUT()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "BASE64_INVALID_INPUT",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "BASE64_INVALID_INPUT",
    data: BytesLike
  ): Result;

  events: {};
}

export interface Base64ErrorCodes extends BaseContract {
  contractName: "Base64ErrorCodes";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: Base64ErrorCodesInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    BASE64_INVALID_INPUT(overrides?: CallOverrides): Promise<[string]>;
  };

  BASE64_INVALID_INPUT(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    BASE64_INVALID_INPUT(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    BASE64_INVALID_INPUT(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    BASE64_INVALID_INPUT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
