/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { OnEvent, TypedEvent, TypedEventFilter, TypedListener } from "./common";

export interface BaseParserLibraryErrorCodesInterface extends utils.Interface {
  contractName: "BaseParserLibraryErrorCodes";
  functions: {
    "BASEPARSERLIB_BE_UINT16_OFFSET_OUT_OF_BOUNDS()": FunctionFragment;
    "BASEPARSERLIB_BE_UINT16_OFFSET_PARAMETER_OVERFLOW()": FunctionFragment;
    "BASEPARSERLIB_BE_UINT256_OFFSET_OUT_OF_BOUNDS()": FunctionFragment;
    "BASEPARSERLIB_BE_UINT256_OFFSET_PARAMETER_OVERFLOW()": FunctionFragment;
    "BASEPARSERLIB_BOOL_OFFSET_OUT_OF_BOUNDS()": FunctionFragment;
    "BASEPARSERLIB_BOOL_OFFSET_PARAMETER_OVERFLOW()": FunctionFragment;
    "BASEPARSERLIB_BYTES32_OFFSET_OUT_OF_BOUNDS()": FunctionFragment;
    "BASEPARSERLIB_BYTES32_OFFSET_PARAMETER_OVERFLOW()": FunctionFragment;
    "BASEPARSERLIB_BYTES_OFFSET_OUT_OF_BOUNDS()": FunctionFragment;
    "BASEPARSERLIB_BYTES_OFFSET_PARAMETER_OVERFLOW()": FunctionFragment;
    "BASEPARSERLIB_LE_UINT16_OFFSET_OUT_OF_BOUNDS()": FunctionFragment;
    "BASEPARSERLIB_LE_UINT16_OFFSET_PARAMETER_OVERFLOW()": FunctionFragment;
    "BASEPARSERLIB_LE_UINT256_OFFSET_OUT_OF_BOUNDS()": FunctionFragment;
    "BASEPARSERLIB_LE_UINT256_OFFSET_PARAMETER_OVERFLOW()": FunctionFragment;
    "BASEPARSERLIB_OFFSET_OUT_OF_BOUNDS()": FunctionFragment;
    "BASEPARSERLIB_OFFSET_PARAMETER_OVERFLOW()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "BASEPARSERLIB_BE_UINT16_OFFSET_OUT_OF_BOUNDS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BASEPARSERLIB_BE_UINT16_OFFSET_PARAMETER_OVERFLOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BASEPARSERLIB_BE_UINT256_OFFSET_OUT_OF_BOUNDS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BASEPARSERLIB_BE_UINT256_OFFSET_PARAMETER_OVERFLOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BASEPARSERLIB_BOOL_OFFSET_OUT_OF_BOUNDS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BASEPARSERLIB_BOOL_OFFSET_PARAMETER_OVERFLOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BASEPARSERLIB_BYTES32_OFFSET_OUT_OF_BOUNDS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BASEPARSERLIB_BYTES32_OFFSET_PARAMETER_OVERFLOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BASEPARSERLIB_BYTES_OFFSET_OUT_OF_BOUNDS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BASEPARSERLIB_BYTES_OFFSET_PARAMETER_OVERFLOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BASEPARSERLIB_LE_UINT16_OFFSET_OUT_OF_BOUNDS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BASEPARSERLIB_LE_UINT16_OFFSET_PARAMETER_OVERFLOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BASEPARSERLIB_LE_UINT256_OFFSET_OUT_OF_BOUNDS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BASEPARSERLIB_LE_UINT256_OFFSET_PARAMETER_OVERFLOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BASEPARSERLIB_OFFSET_OUT_OF_BOUNDS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BASEPARSERLIB_OFFSET_PARAMETER_OVERFLOW",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "BASEPARSERLIB_BE_UINT16_OFFSET_OUT_OF_BOUNDS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BASEPARSERLIB_BE_UINT16_OFFSET_PARAMETER_OVERFLOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BASEPARSERLIB_BE_UINT256_OFFSET_OUT_OF_BOUNDS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BASEPARSERLIB_BE_UINT256_OFFSET_PARAMETER_OVERFLOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BASEPARSERLIB_BOOL_OFFSET_OUT_OF_BOUNDS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BASEPARSERLIB_BOOL_OFFSET_PARAMETER_OVERFLOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BASEPARSERLIB_BYTES32_OFFSET_OUT_OF_BOUNDS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BASEPARSERLIB_BYTES32_OFFSET_PARAMETER_OVERFLOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BASEPARSERLIB_BYTES_OFFSET_OUT_OF_BOUNDS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BASEPARSERLIB_BYTES_OFFSET_PARAMETER_OVERFLOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BASEPARSERLIB_LE_UINT16_OFFSET_OUT_OF_BOUNDS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BASEPARSERLIB_LE_UINT16_OFFSET_PARAMETER_OVERFLOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BASEPARSERLIB_LE_UINT256_OFFSET_OUT_OF_BOUNDS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BASEPARSERLIB_LE_UINT256_OFFSET_PARAMETER_OVERFLOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BASEPARSERLIB_OFFSET_OUT_OF_BOUNDS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BASEPARSERLIB_OFFSET_PARAMETER_OVERFLOW",
    data: BytesLike
  ): Result;

  events: {};
}

export interface BaseParserLibraryErrorCodes extends BaseContract {
  contractName: "BaseParserLibraryErrorCodes";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BaseParserLibraryErrorCodesInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    BASEPARSERLIB_BE_UINT16_OFFSET_OUT_OF_BOUNDS(
      overrides?: CallOverrides
    ): Promise<[string]>;

    BASEPARSERLIB_BE_UINT16_OFFSET_PARAMETER_OVERFLOW(
      overrides?: CallOverrides
    ): Promise<[string]>;

    BASEPARSERLIB_BE_UINT256_OFFSET_OUT_OF_BOUNDS(
      overrides?: CallOverrides
    ): Promise<[string]>;

    BASEPARSERLIB_BE_UINT256_OFFSET_PARAMETER_OVERFLOW(
      overrides?: CallOverrides
    ): Promise<[string]>;

    BASEPARSERLIB_BOOL_OFFSET_OUT_OF_BOUNDS(
      overrides?: CallOverrides
    ): Promise<[string]>;

    BASEPARSERLIB_BOOL_OFFSET_PARAMETER_OVERFLOW(
      overrides?: CallOverrides
    ): Promise<[string]>;

    BASEPARSERLIB_BYTES32_OFFSET_OUT_OF_BOUNDS(
      overrides?: CallOverrides
    ): Promise<[string]>;

    BASEPARSERLIB_BYTES32_OFFSET_PARAMETER_OVERFLOW(
      overrides?: CallOverrides
    ): Promise<[string]>;

    BASEPARSERLIB_BYTES_OFFSET_OUT_OF_BOUNDS(
      overrides?: CallOverrides
    ): Promise<[string]>;

    BASEPARSERLIB_BYTES_OFFSET_PARAMETER_OVERFLOW(
      overrides?: CallOverrides
    ): Promise<[string]>;

    BASEPARSERLIB_LE_UINT16_OFFSET_OUT_OF_BOUNDS(
      overrides?: CallOverrides
    ): Promise<[string]>;

    BASEPARSERLIB_LE_UINT16_OFFSET_PARAMETER_OVERFLOW(
      overrides?: CallOverrides
    ): Promise<[string]>;

    BASEPARSERLIB_LE_UINT256_OFFSET_OUT_OF_BOUNDS(
      overrides?: CallOverrides
    ): Promise<[string]>;

    BASEPARSERLIB_LE_UINT256_OFFSET_PARAMETER_OVERFLOW(
      overrides?: CallOverrides
    ): Promise<[string]>;

    BASEPARSERLIB_OFFSET_OUT_OF_BOUNDS(
      overrides?: CallOverrides
    ): Promise<[string]>;

    BASEPARSERLIB_OFFSET_PARAMETER_OVERFLOW(
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  BASEPARSERLIB_BE_UINT16_OFFSET_OUT_OF_BOUNDS(
    overrides?: CallOverrides
  ): Promise<string>;

  BASEPARSERLIB_BE_UINT16_OFFSET_PARAMETER_OVERFLOW(
    overrides?: CallOverrides
  ): Promise<string>;

  BASEPARSERLIB_BE_UINT256_OFFSET_OUT_OF_BOUNDS(
    overrides?: CallOverrides
  ): Promise<string>;

  BASEPARSERLIB_BE_UINT256_OFFSET_PARAMETER_OVERFLOW(
    overrides?: CallOverrides
  ): Promise<string>;

  BASEPARSERLIB_BOOL_OFFSET_OUT_OF_BOUNDS(
    overrides?: CallOverrides
  ): Promise<string>;

  BASEPARSERLIB_BOOL_OFFSET_PARAMETER_OVERFLOW(
    overrides?: CallOverrides
  ): Promise<string>;

  BASEPARSERLIB_BYTES32_OFFSET_OUT_OF_BOUNDS(
    overrides?: CallOverrides
  ): Promise<string>;

  BASEPARSERLIB_BYTES32_OFFSET_PARAMETER_OVERFLOW(
    overrides?: CallOverrides
  ): Promise<string>;

  BASEPARSERLIB_BYTES_OFFSET_OUT_OF_BOUNDS(
    overrides?: CallOverrides
  ): Promise<string>;

  BASEPARSERLIB_BYTES_OFFSET_PARAMETER_OVERFLOW(
    overrides?: CallOverrides
  ): Promise<string>;

  BASEPARSERLIB_LE_UINT16_OFFSET_OUT_OF_BOUNDS(
    overrides?: CallOverrides
  ): Promise<string>;

  BASEPARSERLIB_LE_UINT16_OFFSET_PARAMETER_OVERFLOW(
    overrides?: CallOverrides
  ): Promise<string>;

  BASEPARSERLIB_LE_UINT256_OFFSET_OUT_OF_BOUNDS(
    overrides?: CallOverrides
  ): Promise<string>;

  BASEPARSERLIB_LE_UINT256_OFFSET_PARAMETER_OVERFLOW(
    overrides?: CallOverrides
  ): Promise<string>;

  BASEPARSERLIB_OFFSET_OUT_OF_BOUNDS(
    overrides?: CallOverrides
  ): Promise<string>;

  BASEPARSERLIB_OFFSET_PARAMETER_OVERFLOW(
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    BASEPARSERLIB_BE_UINT16_OFFSET_OUT_OF_BOUNDS(
      overrides?: CallOverrides
    ): Promise<string>;

    BASEPARSERLIB_BE_UINT16_OFFSET_PARAMETER_OVERFLOW(
      overrides?: CallOverrides
    ): Promise<string>;

    BASEPARSERLIB_BE_UINT256_OFFSET_OUT_OF_BOUNDS(
      overrides?: CallOverrides
    ): Promise<string>;

    BASEPARSERLIB_BE_UINT256_OFFSET_PARAMETER_OVERFLOW(
      overrides?: CallOverrides
    ): Promise<string>;

    BASEPARSERLIB_BOOL_OFFSET_OUT_OF_BOUNDS(
      overrides?: CallOverrides
    ): Promise<string>;

    BASEPARSERLIB_BOOL_OFFSET_PARAMETER_OVERFLOW(
      overrides?: CallOverrides
    ): Promise<string>;

    BASEPARSERLIB_BYTES32_OFFSET_OUT_OF_BOUNDS(
      overrides?: CallOverrides
    ): Promise<string>;

    BASEPARSERLIB_BYTES32_OFFSET_PARAMETER_OVERFLOW(
      overrides?: CallOverrides
    ): Promise<string>;

    BASEPARSERLIB_BYTES_OFFSET_OUT_OF_BOUNDS(
      overrides?: CallOverrides
    ): Promise<string>;

    BASEPARSERLIB_BYTES_OFFSET_PARAMETER_OVERFLOW(
      overrides?: CallOverrides
    ): Promise<string>;

    BASEPARSERLIB_LE_UINT16_OFFSET_OUT_OF_BOUNDS(
      overrides?: CallOverrides
    ): Promise<string>;

    BASEPARSERLIB_LE_UINT16_OFFSET_PARAMETER_OVERFLOW(
      overrides?: CallOverrides
    ): Promise<string>;

    BASEPARSERLIB_LE_UINT256_OFFSET_OUT_OF_BOUNDS(
      overrides?: CallOverrides
    ): Promise<string>;

    BASEPARSERLIB_LE_UINT256_OFFSET_PARAMETER_OVERFLOW(
      overrides?: CallOverrides
    ): Promise<string>;

    BASEPARSERLIB_OFFSET_OUT_OF_BOUNDS(
      overrides?: CallOverrides
    ): Promise<string>;

    BASEPARSERLIB_OFFSET_PARAMETER_OVERFLOW(
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    BASEPARSERLIB_BE_UINT16_OFFSET_OUT_OF_BOUNDS(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    BASEPARSERLIB_BE_UINT16_OFFSET_PARAMETER_OVERFLOW(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    BASEPARSERLIB_BE_UINT256_OFFSET_OUT_OF_BOUNDS(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    BASEPARSERLIB_BE_UINT256_OFFSET_PARAMETER_OVERFLOW(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    BASEPARSERLIB_BOOL_OFFSET_OUT_OF_BOUNDS(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    BASEPARSERLIB_BOOL_OFFSET_PARAMETER_OVERFLOW(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    BASEPARSERLIB_BYTES32_OFFSET_OUT_OF_BOUNDS(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    BASEPARSERLIB_BYTES32_OFFSET_PARAMETER_OVERFLOW(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    BASEPARSERLIB_BYTES_OFFSET_OUT_OF_BOUNDS(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    BASEPARSERLIB_BYTES_OFFSET_PARAMETER_OVERFLOW(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    BASEPARSERLIB_LE_UINT16_OFFSET_OUT_OF_BOUNDS(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    BASEPARSERLIB_LE_UINT16_OFFSET_PARAMETER_OVERFLOW(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    BASEPARSERLIB_LE_UINT256_OFFSET_OUT_OF_BOUNDS(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    BASEPARSERLIB_LE_UINT256_OFFSET_PARAMETER_OVERFLOW(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    BASEPARSERLIB_OFFSET_OUT_OF_BOUNDS(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    BASEPARSERLIB_OFFSET_PARAMETER_OVERFLOW(
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    BASEPARSERLIB_BE_UINT16_OFFSET_OUT_OF_BOUNDS(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    BASEPARSERLIB_BE_UINT16_OFFSET_PARAMETER_OVERFLOW(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    BASEPARSERLIB_BE_UINT256_OFFSET_OUT_OF_BOUNDS(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    BASEPARSERLIB_BE_UINT256_OFFSET_PARAMETER_OVERFLOW(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    BASEPARSERLIB_BOOL_OFFSET_OUT_OF_BOUNDS(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    BASEPARSERLIB_BOOL_OFFSET_PARAMETER_OVERFLOW(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    BASEPARSERLIB_BYTES32_OFFSET_OUT_OF_BOUNDS(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    BASEPARSERLIB_BYTES32_OFFSET_PARAMETER_OVERFLOW(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    BASEPARSERLIB_BYTES_OFFSET_OUT_OF_BOUNDS(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    BASEPARSERLIB_BYTES_OFFSET_PARAMETER_OVERFLOW(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    BASEPARSERLIB_LE_UINT16_OFFSET_OUT_OF_BOUNDS(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    BASEPARSERLIB_LE_UINT16_OFFSET_PARAMETER_OVERFLOW(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    BASEPARSERLIB_LE_UINT256_OFFSET_OUT_OF_BOUNDS(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    BASEPARSERLIB_LE_UINT256_OFFSET_PARAMETER_OVERFLOW(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    BASEPARSERLIB_OFFSET_OUT_OF_BOUNDS(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    BASEPARSERLIB_OFFSET_PARAMETER_OVERFLOW(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
