/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { OnEvent, TypedEvent, TypedEventFilter, TypedListener } from "./common";

export interface MockBaseContractInterface extends utils.Interface {
  contractName: "MockBaseContract";
  functions: {
    "fail()": FunctionFragment;
    "getFactory()": FunctionFragment;
    "getImut()": FunctionFragment;
    "getVar()": FunctionFragment;
    "getpString()": FunctionFragment;
    "lock()": FunctionFragment;
    "payMe()": FunctionFragment;
    "setFactory(address)": FunctionFragment;
    "setV(uint256)": FunctionFragment;
    "unlock()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "fail", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getFactory",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getImut", values?: undefined): string;
  encodeFunctionData(functionFragment: "getVar", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getpString",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "lock", values?: undefined): string;
  encodeFunctionData(functionFragment: "payMe", values?: undefined): string;
  encodeFunctionData(functionFragment: "setFactory", values: [string]): string;
  encodeFunctionData(functionFragment: "setV", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "unlock", values?: undefined): string;

  decodeFunctionResult(functionFragment: "fail", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getFactory", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getImut", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getVar", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getpString", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lock", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payMe", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setFactory", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setV", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unlock", data: BytesLike): Result;

  events: {};
}

export interface MockBaseContract extends BaseContract {
  contractName: "MockBaseContract";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MockBaseContractInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    fail(overrides?: CallOverrides): Promise<[void]>;

    getFactory(overrides?: CallOverrides): Promise<[string]>;

    getImut(overrides?: CallOverrides): Promise<[BigNumber]>;

    getVar(overrides?: CallOverrides): Promise<[BigNumber]>;

    getpString(overrides?: CallOverrides): Promise<[string]>;

    lock(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    payMe(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setFactory(
      factory_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setV(
      _v: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    unlock(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  fail(overrides?: CallOverrides): Promise<void>;

  getFactory(overrides?: CallOverrides): Promise<string>;

  getImut(overrides?: CallOverrides): Promise<BigNumber>;

  getVar(overrides?: CallOverrides): Promise<BigNumber>;

  getpString(overrides?: CallOverrides): Promise<string>;

  lock(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  payMe(
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setFactory(
    factory_: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setV(
    _v: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  unlock(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    fail(overrides?: CallOverrides): Promise<void>;

    getFactory(overrides?: CallOverrides): Promise<string>;

    getImut(overrides?: CallOverrides): Promise<BigNumber>;

    getVar(overrides?: CallOverrides): Promise<BigNumber>;

    getpString(overrides?: CallOverrides): Promise<string>;

    lock(overrides?: CallOverrides): Promise<void>;

    payMe(overrides?: CallOverrides): Promise<void>;

    setFactory(factory_: string, overrides?: CallOverrides): Promise<void>;

    setV(_v: BigNumberish, overrides?: CallOverrides): Promise<void>;

    unlock(overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    fail(overrides?: CallOverrides): Promise<BigNumber>;

    getFactory(overrides?: CallOverrides): Promise<BigNumber>;

    getImut(overrides?: CallOverrides): Promise<BigNumber>;

    getVar(overrides?: CallOverrides): Promise<BigNumber>;

    getpString(overrides?: CallOverrides): Promise<BigNumber>;

    lock(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    payMe(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setFactory(
      factory_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setV(
      _v: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    unlock(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    fail(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getFactory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getImut(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getVar(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getpString(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lock(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    payMe(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setFactory(
      factory_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setV(
      _v: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    unlock(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
