/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { OnEvent, TypedEvent, TypedEventFilter, TypedListener } from "./common";

export interface RCertParserLibraryErrorCodesInterface extends utils.Interface {
  contractName: "RCertParserLibraryErrorCodes";
  functions: {
    "RCERTPARSERLIB_DATA_OFFSET_OVERFLOW()": FunctionFragment;
    "RCERTPARSERLIB_INSUFFICIENT_BYTES()": FunctionFragment;
    "RCERTPARSERLIB_INSUFFICIENT_BYTES_TO_EXTRACT()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "RCERTPARSERLIB_DATA_OFFSET_OVERFLOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RCERTPARSERLIB_INSUFFICIENT_BYTES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RCERTPARSERLIB_INSUFFICIENT_BYTES_TO_EXTRACT",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "RCERTPARSERLIB_DATA_OFFSET_OVERFLOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RCERTPARSERLIB_INSUFFICIENT_BYTES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RCERTPARSERLIB_INSUFFICIENT_BYTES_TO_EXTRACT",
    data: BytesLike
  ): Result;

  events: {};
}

export interface RCertParserLibraryErrorCodes extends BaseContract {
  contractName: "RCertParserLibraryErrorCodes";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RCertParserLibraryErrorCodesInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    RCERTPARSERLIB_DATA_OFFSET_OVERFLOW(
      overrides?: CallOverrides
    ): Promise<[string]>;

    RCERTPARSERLIB_INSUFFICIENT_BYTES(
      overrides?: CallOverrides
    ): Promise<[string]>;

    RCERTPARSERLIB_INSUFFICIENT_BYTES_TO_EXTRACT(
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  RCERTPARSERLIB_DATA_OFFSET_OVERFLOW(
    overrides?: CallOverrides
  ): Promise<string>;

  RCERTPARSERLIB_INSUFFICIENT_BYTES(overrides?: CallOverrides): Promise<string>;

  RCERTPARSERLIB_INSUFFICIENT_BYTES_TO_EXTRACT(
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    RCERTPARSERLIB_DATA_OFFSET_OVERFLOW(
      overrides?: CallOverrides
    ): Promise<string>;

    RCERTPARSERLIB_INSUFFICIENT_BYTES(
      overrides?: CallOverrides
    ): Promise<string>;

    RCERTPARSERLIB_INSUFFICIENT_BYTES_TO_EXTRACT(
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    RCERTPARSERLIB_DATA_OFFSET_OVERFLOW(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    RCERTPARSERLIB_INSUFFICIENT_BYTES(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    RCERTPARSERLIB_INSUFFICIENT_BYTES_TO_EXTRACT(
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    RCERTPARSERLIB_DATA_OFFSET_OVERFLOW(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    RCERTPARSERLIB_INSUFFICIENT_BYTES(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    RCERTPARSERLIB_INSUFFICIENT_BYTES_TO_EXTRACT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
