-name: create a disk
google.cloud.gcp_compute_disk:
  name: testnet-disk-instance
  size_gb: {{disk_size}}
  source_image: projects/ubuntu-os-cloud/global/images/family/ubuntu-1604-lts
  zone: {{zone}}
  project: "{{gcp_project}}"
  auth_kind: "{{gcp_cred_kind}}"
  service_account_file: "{{gcp_cred_file}}"
  state: present
register: disk

- name: create a network
google.cloud.gcp_compute_network:
  name: testnet-network-instance
  auto_create_subnetworks: no
  project: "{{gcp_project}}"
  auth_kind: "{{gcp_cred_kind}}"
  service_account_file: "{{gcp_cred_file}}"
  state: present
register: network

- name: create a address
google.cloud.gcp_compute_address:
  name: testnet-address-instance