// Generated by ifacemaker. DO NOT EDIT.

package bindings

import (
	"math/big"

	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/core/types"
)

// IGovernanceTransactor ...
type IGovernanceTransactor interface {
	// UpdateValue is a paid mutator transaction binding the contract method 0x46512486.
	//
	// Solidity: function updateValue(uint256 epoch, uint256 key, bytes32 value) returns()
	UpdateValue(opts *bind.TransactOpts, epoch *big.Int, key *big.Int, value [32]byte) (*types.Transaction, error)
}
