// Generated by custom bridge script. DO NOT EDIT

package bindings

type IAToken interface {
	IATokenCaller
	IATokenTransactor
	IATokenFilterer
}

type IATokenBurner interface {
	IATokenBurnerCaller
	IATokenBurnerTransactor
	IATokenBurnerFilterer
}

type IATokenMinter interface {
	IATokenMinterCaller
	IATokenMinterTransactor
	IATokenMinterFilterer
}

type IAliceNetFactory interface {
	IAliceNetFactoryCaller
	IAliceNetFactoryTransactor
	IAliceNetFactoryFilterer
}

type IBToken interface {
	IBTokenCaller
	IBTokenTransactor
	IBTokenFilterer
}

type IETHDKG interface {
	IETHDKGCaller
	IETHDKGTransactor
	IETHDKGFilterer
}

type IETHDKGErrors interface {
	IETHDKGErrorsCaller
	IETHDKGErrorsTransactor
	IETHDKGErrorsFilterer
}

type IGovernance interface {
	IGovernanceCaller
	IGovernanceTransactor
	IGovernanceFilterer
}

type IGovernanceErrors interface {
	IGovernanceErrorsCaller
	IGovernanceErrorsTransactor
	IGovernanceErrorsFilterer
}

type IPublicStaking interface {
	IPublicStakingCaller
	IPublicStakingTransactor
	IPublicStakingFilterer
}

type ISnapshots interface {
	ISnapshotsCaller
	ISnapshotsTransactor
	ISnapshotsFilterer
}

type ISnapshotsErrors interface {
	ISnapshotsErrorsCaller
	ISnapshotsErrorsTransactor
	ISnapshotsErrorsFilterer
}

type IValidatorPool interface {
	IValidatorPoolCaller
	IValidatorPoolTransactor
	IValidatorPoolFilterer
}

type IValidatorPoolErrors interface {
	IValidatorPoolErrorsCaller
	IValidatorPoolErrorsTransactor
	IValidatorPoolErrorsFilterer
}

type IValidatorStaking interface {
	IValidatorStakingCaller
	IValidatorStakingTransactor
	IValidatorStakingFilterer
}
