run:
  timeout: 5m
  build-tags:
    - integration
    - flakes
linters:
  enable:
    - gci
    - godot
    - gofumpt
    - misspell
    - whitespace
  # Disabling linters until we get them fixed up.
  disable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - varcheck
linters-settings:
  gofumpt:
    lang-version: "1.18"
    module-path: github.com/alicenet/alicenet
    extra-rules: true
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/alicenet)
