run:
  timeout: 5m
  build-tags:
    - integration
    - flakes
linters:
  enable:
    - errcheck
    - govet
  # Disabling linters until we get them fixed up.
  disable:
    - gosimple
    - ineffassign
    - staticcheck
