run:
  timeout: 5m
  build-tags:
    - integration
    - flakes
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
  # Disabling linters until we get them fixed up.
  disable:
    - staticcheck
