/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";
import type {
  CircuitBreaker,
  CircuitBreakerInterface,
} from "../CircuitBreaker";

const _abi = [
  {
    inputs: [],
    name: "cbState",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class CircuitBreaker__factory {
  static readonly abi = _abi;
  static createInterface(): CircuitBreakerInterface {
    return new utils.Interface(_abi) as CircuitBreakerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CircuitBreaker {
    return new Contract(address, _abi, signerOrProvider) as CircuitBreaker;
  }
}
