/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";
import type { IATokenBurner, IATokenBurnerInterface } from "../IATokenBurner";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "burn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IATokenBurner__factory {
  static readonly abi = _abi;
  static createInterface(): IATokenBurnerInterface {
    return new utils.Interface(_abi) as IATokenBurnerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IATokenBurner {
    return new Contract(address, _abi, signerOrProvider) as IATokenBurner;
  }
}
