/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";
import type { ICBCloser, ICBCloserInterface } from "../ICBCloser";

const _abi = [
  {
    inputs: [],
    name: "resetCB",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ICBCloser__factory {
  static readonly abi = _abi;
  static createInterface(): ICBCloserInterface {
    return new utils.Interface(_abi) as ICBCloserInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICBCloser {
    return new Contract(address, _abi, signerOrProvider) as ICBCloser;
  }
}
