/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";
import type { ICBOpener, ICBOpenerInterface } from "../ICBOpener";

const _abi = [
  {
    inputs: [],
    name: "tripCB",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ICBOpener__factory {
  static readonly abi = _abi;
  static createInterface(): ICBOpenerInterface {
    return new utils.Interface(_abi) as ICBOpenerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICBOpener {
    return new Contract(address, _abi, signerOrProvider) as ICBOpener;
  }
}
