/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";
import type { IETHDKGEvents, IETHDKGEventsInterface } from "../IETHDKGEvents";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "nonce",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256[2]",
        name: "publicKey",
        type: "uint256[2]",
      },
    ],
    name: "AddressRegistered",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "blockNumber",
        type: "uint256",
      },
    ],
    name: "GPKJSubmissionComplete",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "blockNumber",
        type: "uint256",
      },
    ],
    name: "KeyShareSubmissionComplete",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "nonce",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256[2]",
        name: "keyShareG1",
        type: "uint256[2]",
      },
      {
        indexed: false,
        internalType: "uint256[2]",
        name: "keyShareG1CorrectnessProof",
        type: "uint256[2]",
      },
      {
        indexed: false,
        internalType: "uint256[4]",
        name: "keyShareG2",
        type: "uint256[4]",
      },
    ],
    name: "KeyShareSubmitted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "blockNumber",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "nonce",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256[4]",
        name: "mpk",
        type: "uint256[4]",
      },
    ],
    name: "MPKSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "blockNumber",
        type: "uint256",
      },
    ],
    name: "RegistrationComplete",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "startBlock",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "numberValidators",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "nonce",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "phaseLength",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "confirmationLength",
        type: "uint256",
      },
    ],
    name: "RegistrationOpened",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "blockNumber",
        type: "uint256",
      },
    ],
    name: "ShareDistributionComplete",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "nonce",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "encryptedShares",
        type: "uint256[]",
      },
      {
        indexed: false,
        internalType: "uint256[2][]",
        name: "commitments",
        type: "uint256[2][]",
      },
    ],
    name: "SharesDistributed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "nonce",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "epoch",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "share0",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "share1",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "share2",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "share3",
        type: "uint256",
      },
    ],
    name: "ValidatorMemberAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "validatorCount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "nonce",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "epoch",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "ethHeight",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "aliceNetHeight",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "groupKey0",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "groupKey1",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "groupKey2",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "groupKey3",
        type: "uint256",
      },
    ],
    name: "ValidatorSetCompleted",
    type: "event",
  },
];

export class IETHDKGEvents__factory {
  static readonly abi = _abi;
  static createInterface(): IETHDKGEventsInterface {
    return new utils.Interface(_abi) as IETHDKGEventsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IETHDKGEvents {
    return new Contract(address, _abi, signerOrProvider) as IETHDKGEvents;
  }
}
