/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";
import type {
  ImmutablePublicStaking,
  ImmutablePublicStakingInterface,
} from "../ImmutablePublicStaking";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_salt",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "_factory",
        type: "address",
      },
    ],
    name: "getMetamorphicContractAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

export class ImmutablePublicStaking__factory {
  static readonly abi = _abi;
  static createInterface(): ImmutablePublicStakingInterface {
    return new utils.Interface(_abi) as ImmutablePublicStakingInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ImmutablePublicStaking {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ImmutablePublicStaking;
  }
}
