/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";
import type {
  ImmutableStakingPositionDescriptor,
  ImmutableStakingPositionDescriptorInterface,
} from "../ImmutableStakingPositionDescriptor";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_salt",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "_factory",
        type: "address",
      },
    ],
    name: "getMetamorphicContractAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

export class ImmutableStakingPositionDescriptor__factory {
  static readonly abi = _abi;
  static createInterface(): ImmutableStakingPositionDescriptorInterface {
    return new utils.Interface(
      _abi
    ) as ImmutableStakingPositionDescriptorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ImmutableStakingPositionDescriptor {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ImmutableStakingPositionDescriptor;
  }
}
