/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides, Signer, utils } from "ethers";
import type {
  MagicValueErrorCodes,
  MagicValueErrorCodesInterface,
} from "../MagicValueErrorCodes";

const _abi = [
  {
    inputs: [],
    name: "MAGICVALUE_BAD_MAGIC",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x60a6610038600b82828239805160001a607314602b57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c80634e2adbcf146038575b600080fd5b605e7f323230300000000000000000000000000000000000000000000000000000000081565b60405190815260200160405180910390f3fea26469706673582212208b0a6c9dfee264b869690a9480632205e3a7a554af70c28f73d0c70d8153405764736f6c634300080d0033";

type MagicValueErrorCodesConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MagicValueErrorCodesConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MagicValueErrorCodes__factory extends ContractFactory {
  constructor(...args: MagicValueErrorCodesConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "MagicValueErrorCodes";
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<MagicValueErrorCodes> {
    return super.deploy(overrides || {}) as Promise<MagicValueErrorCodes>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): MagicValueErrorCodes {
    return super.attach(address) as MagicValueErrorCodes;
  }
  connect(signer: Signer): MagicValueErrorCodes__factory {
    return super.connect(signer) as MagicValueErrorCodes__factory;
  }
  static readonly contractName: "MagicValueErrorCodes";
  public readonly contractName: "MagicValueErrorCodes";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MagicValueErrorCodesInterface {
    return new utils.Interface(_abi) as MagicValueErrorCodesInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MagicValueErrorCodes {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as MagicValueErrorCodes;
  }
}
