name: 'Setup golang and its cache'
description: 'Setup golang and its cache'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v3
      with:
        go-version-file: ./go.mod
        cache: true
