@startuml
left to right direction
skinparam actorStyle awesome
skinparam usecase {
BackgroundColor DarkSeaGreen
BorderColor DarkSlateGray
ArrowColor Olive
}
actor User
package BridgePool {
  usecase deposit
}
package BridgePoolFactory {
  usecase deployNewPool
  usecase deployViaFactoryLogic as "
  deployViaFactoryLogic
  ==
  deployTemplate
  deployCreate
  deployProxy
  upgradeProxy
"
}
package AliceNetFactory {
  usecase delegateCallAny
}

User --> deployNewPool :1
deployNewPool --> delegateCallAny :2
delegateCallAny --> deployViaFactoryLogic :3
deployViaFactoryLogic --> BridgePool: "4 BridgePool Creation"
User --> deposit : 5
@enduml