@startuml name
Actor User
Participant "MadnetFactory" as MadnetFactory #LightBlue
Participant "ALCA\n(New ERC20Upgradeable)" as ALCA #LightGreen
Participant "MadToken\n(Legacy ERC20)" as MadToken #Orange
Participant "ALCAMinter" as ALCAMinter #LightCoral
Participant "ALCABurner" as ALCABurner #LightCyan
title New ERC20Upgradeable ALCA with External Minter/Burner Helper

group setup    [onlyFactory]
    MadnetFactory -> ALCA : new ALCA(MadToken)
end
User -> MadToken : approve(ALCA,amount)
User -> ALCA : migrate(amount)
group migrate
    group burn
        ALCA -> MadToken : transferFrom\n(user,ALCA,amount)
        MadToken --> ALCA: MadToken amount
    end
    group mint
        ALCA -> ALCA : _mint(user, amount)
        ALCA --> User: ALCA amount
    end
end
User -> ALCABurner : burn(user,amount) [onlyFactory]
group externalBurn
    ALCABurner -> ALCA : externalBurn(user, amount)\n[onlyALCABurner]
    ALCA -> ALCA : _burn(user, amount)
    User --> ALCA: ALCA amount
end
User -> ALCAMinter : mint(user,amount) [onlyFactory]
group externalMint
    ALCAMinter -> ALCA : externalMint(user, amount)\n[onlyALCAMinter]
    ALCA -> ALCA : _mint(user, amount)
    ALCA --> User: ALCA amount
end
@enduml


