// Generated by ifacemaker. DO NOT EDIT.

package ethereum

import (
	"math/big"

	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
)

// IALCBCaller ...
type IALCBCaller interface {
	// Allowance is a free data retrieval call binding the contract method 0xdd62ed3e.
	//
	// Solidity: function allowance(address owner, address spender) view returns(uint256)
	Allowance(opts *bind.CallOpts, owner common.Address, spender common.Address) (*big.Int, error)
	// BalanceOf is a free data retrieval call binding the contract method 0x70a08231.
	//
	// Solidity: function balanceOf(address account) view returns(uint256)
	BalanceOf(opts *bind.CallOpts, account common.Address) (*big.Int, error)
	// Decimals is a free data retrieval call binding the contract method 0x313ce567.
	//
	// Solidity: function decimals() view returns(uint8)
	Decimals(opts *bind.CallOpts) (uint8, error)
	// GetCentralBridgeRouterAddress is a free data retrieval call binding the contract method 0xff32fefc.
	//
	// Solidity: function getCentralBridgeRouterAddress() view returns(address)
	GetCentralBridgeRouterAddress(opts *bind.CallOpts) (common.Address, error)
	// GetDeposit is a free data retrieval call binding the contract method 0x9f9fb968.
	//
	// Solidity: function getDeposit(uint256 depositID) view returns((uint8,address,uint256))
	GetDeposit(opts *bind.CallOpts, depositID *big.Int) (Deposit, error)
	// GetDepositID is a free data retrieval call binding the contract method 0x94f70c8a.
	//
	// Solidity: function getDepositID() view returns(uint256)
	GetDepositID(opts *bind.CallOpts) (*big.Int, error)
	// GetEthFromTokensBurn is a free data retrieval call binding the contract method 0xc67cb8d1.
	//
	// Solidity: function getEthFromTokensBurn(uint256 poolBalance_, uint256 totalSupply_, uint256 numBTK_) pure returns(uint256 numEth)
	GetEthFromTokensBurn(opts *bind.CallOpts, poolBalance_ *big.Int, totalSupply_ *big.Int, numBTK_ *big.Int) (*big.Int, error)
	// GetEthToMintTokens is a free data retrieval call binding the contract method 0x688727c5.
	//
	// Solidity: function getEthToMintTokens(uint256 totalSupply_, uint256 numBTK_) pure returns(uint256 numEth)
	GetEthToMintTokens(opts *bind.CallOpts, totalSupply_ *big.Int, numBTK_ *big.Int) (*big.Int, error)
	// GetLatestEthFromTokensBurn is a free data retrieval call binding the contract method 0xe51b55e3.
	//
	// Solidity: function getLatestEthFromTokensBurn(uint256 numBTK_) view returns(uint256 numEth)
	GetLatestEthFromTokensBurn(opts *bind.CallOpts, numBTK_ *big.Int) (*big.Int, error)
	// GetLatestEthToMintTokens is a free data retrieval call binding the contract method 0xf14a28f9.
	//
	// Solidity: function getLatestEthToMintTokens(uint256 numBTK_) view returns(uint256 numEth)
	GetLatestEthToMintTokens(opts *bind.CallOpts, numBTK_ *big.Int) (*big.Int, error)
	// GetLatestMintedTokensFromEth is a free data retrieval call binding the contract method 0x46711773.
	//
	// Solidity: function getLatestMintedTokensFromEth(uint256 numEth_) view returns(uint256)
	GetLatestMintedTokensFromEth(opts *bind.CallOpts, numEth_ *big.Int) (*big.Int, error)
	// GetMarketSpread is a free data retrieval call binding the contract method 0x086cfefd.
	//
	// Solidity: function getMarketSpread() pure returns(uint256)
	GetMarketSpread(opts *bind.CallOpts) (*big.Int, error)
	// GetMetamorphicContractAddress is a free data retrieval call binding the contract method 0x8653a465.
	//
	// Solidity: function getMetamorphicContractAddress(bytes32 _salt, address _factory) pure returns(address)
	GetMetamorphicContractAddress(opts *bind.CallOpts, _salt [32]byte, _factory common.Address) (common.Address, error)
	// GetMintedTokensFromEth is a free data retrieval call binding the contract method 0x679f742d.
	//
	// Solidity: function getMintedTokensFromEth(uint256 poolBalance_, uint256 numEth_) pure returns(uint256)
	GetMintedTokensFromEth(opts *bind.CallOpts, poolBalance_ *big.Int, numEth_ *big.Int) (*big.Int, error)
	// GetPoolBalance is a free data retrieval call binding the contract method 0xabd70aa2.
	//
	// Solidity: function getPoolBalance() view returns(uint256)
	GetPoolBalance(opts *bind.CallOpts) (*big.Int, error)
	// GetTotalTokensDeposited is a free data retrieval call binding the contract method 0x8d407823.
	//
	// Solidity: function getTotalTokensDeposited() view returns(uint256)
	GetTotalTokensDeposited(opts *bind.CallOpts) (*big.Int, error)
	// GetYield is a free data retrieval call binding the contract method 0x7c262871.
	//
	// Solidity: function getYield() view returns(uint256)
	GetYield(opts *bind.CallOpts) (*big.Int, error)
	// Name is a free data retrieval call binding the contract method 0x06fdde03.
	//
	// Solidity: function name() view returns(string)
	Name(opts *bind.CallOpts) (string, error)
	// Symbol is a free data retrieval call binding the contract method 0x95d89b41.
	//
	// Solidity: function symbol() view returns(string)
	Symbol(opts *bind.CallOpts) (string, error)
	// TotalSupply is a free data retrieval call binding the contract method 0x18160ddd.
	//
	// Solidity: function totalSupply() view returns(uint256)
	TotalSupply(opts *bind.CallOpts) (*big.Int, error)
}
