[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test_sol'
cache_path = 'forge_cache'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config